geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/profile/', authapp.edit, name='edit'),
    path('user/register/', authapp.register, name='register'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import settings
from .views import main, contact

app_name = 'geekshop'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', main, name='index'),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp

app_name = 'ordersapp'


urlpatterns = [

    path('', ordersapp.OrderList.as_view(), name='index'),
    path('create/', ordersapp.OrderCreate.as_view(), name='create'),
    path('read/<pk>/', ordersapp.OrderRead.as_view(), name='read'),
    path('update/<pk>/', ordersapp.OrderUpdate.as_view(), name='update'),
    path('delete/<pk>/', ordersapp.OrderDelete.as_view(), name='delete'),

    path('forming/complete/<pk>/', ordersapp.forming_complete, name='forming_complete'),

    path('product/<int:pk>/price/', ordersapp.get_product_price),
]

geekshop/ordersapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders')
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    @property
    def is_forming(self):
        return self.status == self.FORMING

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    @property
    def total_quantity(self):
        return sum(map(lambda x: x.quantity, self.items.all()))


    def get_total_cost(self):
        return sum(map(lambda x: x.product_cost, self.items.all()))

    # переопределяем метод, удаляющий объект
    def delete(self, using=None, keep_parent=False):
        for item in self.items.all():
            item.product.quantity += item.quantity
            item.product.save()
        # print('Order delete')
        # self.items.delete()
        self.is_active = False
        self.save()
        # super().delete()


class OrderItemManager(models.QuerySet):
    def delete(self):
        print('OrderItemManager QS delete')
        super().delete()


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              on_delete=models.CASCADE,
                              related_name='items')
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(verbose_name='количество',
                                           default=0)

    # objectss = OrderItemManager.as_manager()

    @property
    def product_cost(self):
        return self.product.price * self.quantity


    @classmethod
    def get_item(cls, pk):
        return cls.objects.filter(pk=pk).first()

    # def delete(self, using=None, keep_parents=None):
    #     print('OrderItem instance delete')
    #     super().delete(using, keep_parents)

geekshop/ordersapp/forms.py
from django import forms
from django.forms import HiddenInput

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class BaseOrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'user':
                field.widget = HiddenInput()
            field.widget.attrs['class'] = 'form-control'


class OrderForm(BaseOrderForm):
    class Meta:
        model = Order
        fields = ('user',)


class OrderItemForm(BaseOrderForm):
    price = forms.FloatField(label='цена за 1 ед', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.get_items()

    # Не работает
    def clean_quantity(self):
        quantity = self.cleaned_data.get('quantity')
        product = self.cleaned_data.get('product')
        if quantity > product.quantity:
            raise forms.ValidationError("Недостаточно товара на складе!")
        return quantity


    class Meta:
        model = OrderItem
        fields = '__all__'

geekshop/ordersapp/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DeleteView, DetailView, UpdateView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.forms import OrderForm, OrderItemForm
from ordersapp.models import Order, OrderItem


class PageTitleMixin:
    page_title_key = 'page_title'
    page_title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.page_title_key] = self.page_title
        return context


class OrderList(PageTitleMixin, ListView):
    model = Order
    page_title = 'список заказов'

    def get_queryset(self):
        return self.request.user.orders.all()


class OrderCreate(PageTitleMixin, CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('orders:index')
    page_title = 'создание заказа'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem,
                                             form=OrderItemForm, extra=2)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, self.request.FILES)
        else:
            context['form'].initial['user'] = self.request.user
            basket_items = self.request.user.basket.all()
            if basket_items.exists():
                OrderFormSet = inlineformset_factory(
                    Order, OrderItem, form=OrderItemForm, extra=basket_items.count() + 1
                )
                formset = OrderFormSet()
                for form, basket_item in zip(formset.forms, basket_items):
                    form.initial['product'] = basket_item.product
                    form.initial['quantity'] = basket_item.quantity
            else:
                formset = OrderFormSet()

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            order = super().form_valid(form)
            if orderitems.is_valid():
                orderitems.instance = self.object  # one to many
                orderitems.save()
                self.request.user.basket.all().delete()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return order


class OrderUpdate(PageTitleMixin, UpdateView, ):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy('orders:index')
    page_title = 'редактирование заказа'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                instance = form.instance
                if instance.pk:
                    form.initial['price'] = instance.product.price

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            order = super().form_valid(form)
            if orderitems.is_valid():
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return order


class OrderDelete(PageTitleMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:index')
    page_title = 'удаление заказа'


class OrderRead(PageTitleMixin, DetailView):
    model = Order
    page_title = 'просмотр заказа'


def forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('orders:index'))


@receiver(pre_save, sender=OrderItem)
# @receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if instance.pk:
        instance.product.quantity += sender.get_item(instance.pk).quantity - instance.quantity
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=OrderItem)
# @receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=Order)
def product_quantity_update_delete(sender, instance, **kwargs):
    print('order delete')


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=pk).first()
        # return JsonResponse({'price': product.price if product else 0})
        return JsonResponse({'price': product and product.price or 0})

geekshop/ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <meta charset="utf-8">
	<title>
		{{ page_title|default:'магазин'|capfirst }}
	</title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/jquery.formset.js' %}"></script>
<!--        <script src="{% static 'js/orders_script.js' %}"></script>-->
        <script src="{% static 'js/orders_scripts.js' %}"></script>
    {% endblock %}
<body>
  <div class="basket_container">
       {% block container %}
       {% endblock %}
  </div>

</body>
</html>

geekshop/ordersapp/templates/ordersapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Заказы</title>
</head>
<body>
    <a href="{% url 'orders:create' %}">новый заказ</a>
</body>
</html>

geekshop/ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block container %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
           {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'orders:delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'orders:index' %}">отмена</a>
       </button>
   </div>
{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_detail.html
{% extends 'ordersapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block container %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.items.all %}
           <div class="basket_record">
               <img src="{{ item.product.image|media_folder_products }}" alt="{{ item.product.short_desc }}">

               <span class="category_name">{{ item.product.category.name }}</span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">{{ item.product.price }}руб</span>
               <span class="product_quantity">x{{ item.quantity }}шт.</span>
               <span class="product_cost">={{ item.product_cost }}руб</span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block container %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                   {{ field.label|lower }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                                   {{ field.errors.as_ul }}
                               {% if field.name == 'price' %}
                                   <span class="items-{{ forloop.parentloop.counter0 }}-price">
                                       {{ field.value|default:"0,00" }}
                                   </span>руб
                               {% else %}
                                   {{ field|lower }}
                               {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
           {% include 'ordersapp/includes/inc_order_actions.html' %}
       </form>
   </div>

{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}


{% block container %}
   <div class="h2 text-center head">
       Ваши заказы,
       {% if user.first_name %}{{ user.first_name|title}}{% else %}Пользователь{% endif %}
   </div>
   <table class="table">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'orders:read' item.pk %}">посмотреть</a>
                   </td>
                   <td>
                       {% if item.is_forming %}
                         <a href="{% url 'orders:update' item.pk %}">редактировать</a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.is_forming %}
                         <a href="{% url 'orders:delete' item.pk %}">удалить</a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
    <div class="text-center">
        <button class="btn btn-default btn-round">
           <a href="{% url 'index' %}">на главную</a>
       </button>
       <button class="btn btn-default btn-round">
           <a href="{% url 'orders:create' %}">новый</a>
       </button>
    </div>
{% endblock %}