geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/profile/', authapp.edit, name='edit'),
    path('user/register/', authapp.register, name='register'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import settings
from .views import main, contact

app_name = 'geekshop'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', main, name='index'),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/geekshop/views.py
from django.shortcuts import render
from basketapp.models import Basket


def main(request):
    basket = ''
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    context = {
        'page_title': 'главная',
    }
    return render(request, 'index.html', context)


def contact(request):
    locations = [
        {'city': 'Екатеринбург',
         'phone': '+7-777-777-7777',
         'email': 'ekb-info@geekshop.ru',
         'address': 'В пределах ЕКАД'
         },
        {'city': 'Москва',
         'phone': '+7-888-888-8888',
         'email': 'msk-info@geekshop.ru',
         'address': 'В пределах МКАД'
         },
        {'city': 'Санкт-Петербург',
         'phone': '+7-999-999-9999',
         'email': 'spb-info@geekshop.ru',
         'address': 'В пределах КАД'
         },
    ]
    context = {
        'page_title': 'контакты',
        'locations': locations,
    }
    return render(request, 'contact.html', context)

geekshop/geekshop/templates/includes/inc_catalog.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'category' 0 %}" class="{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk == 0 %}active{% endif %}">все</a></li>

        {% for category in categories %}
            <li>
              <a href="{% url 'category' category.pk %}" class="{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk == category.pk %}active{% endif %}">
                {{ category.name }}
              </a>
            </li>
        {% endfor %}
    </ul>
</div>

geekshop/geekshop/templates/includes/inc_menu.html
{% load static %}

<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}"
               class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
            домой
        </a></li>
        <li><a href="{% url 'products' %}"
               class="{% if request.resolver_match.url_name == 'products' or request.resolver_match.url_name == 'category' %}active{% endif %}">
            продукты
        </a></li>
        <li><a href="{% url 'contact' %}"
               class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
            контакты
        </a></li>

        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit' %}">{{ user.first_name|default:'Пользователь'|capfirst }}
                </a>
            </li>
        {% endif %}
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'my_admin:index' %}">
                    Админка
                </a>
            </li>
        {% endif %}
            <li>
               <a href="{% url 'orders:index' %}">заказы</a>
            </li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">выйти</a>
                {% else %}
                <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:index' %}" class="basket">
        {% if user.is_authenticated %}
        <span>
            {{ user.basket_price|floatformat:0 }}руб ({{ user.basket_quantity }}шт)
        </span>
        {% endif %}
    </a>
</div>