geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'


urlpatterns = [
    path('', adminapp.index, name='index'),
    # path('user/update/<int:user_pk>', adminapp.user_update, name='user_update'),
    path('user/update/<int:user_pk>', adminapp.ShopUserAdminUpdate.as_view(), name='user_update'),

    path('user/delete/<int:user_pk>', adminapp.user_delete, name='user_delete'),

    # path('categories/', adminapp.categories, name='categories'),
    path('categories/', adminapp.ProductCategoryList.as_view(), name='categories'),

    path('category/create/', adminapp.ProductCategoryCreate.as_view(), name='category_create'),
    path('category/update/<int:pk>', adminapp.ProductCategoryUpdate.as_view(), name='category_update'),

    path('category/delete/<int:pk>', adminapp.ProductCategoryDelete.as_view(), name='category_delete'),
    path('category/<int:pk>/products/', adminapp.category_products, name='category_products'),
    path('category/<int:category_pk>/products/create/', adminapp.category_product_create, name='category_product_create'),

    path('product/<int:pk>/', adminapp.ProductDetail.as_view(), name='product_view'),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/profile/', authapp.edit, name='edit'),
    path('user/register/', authapp.register, name='register'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import settings
from .views import main, contact

app_name = 'geekshop'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', main, name='index'),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import category, products, product_page
urlpatterns = [
    path('', products, name='products'),
    path('category/<pk>/', category, name='category'),
    path('product/<pk>/', product_page, name='product_page'),
]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        'имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        'описание',
        blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name} ({self.updated})'

    class Meta:
        verbose_name = 'категория продукта'
        verbose_name_plural = 'категории продукта'
        ordering = ['name']

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE,)
    name = models.CharField('имя', max_length=128,)
    image = models.ImageField(upload_to='product_img', blank=True,)
    short_desc = models.CharField(
        'краткое описание',
        max_length=256,
        blank=True,
    )
    description = models.CharField(
        'описание',
        max_length=500,
        blank=True,
    )
    price = models.DecimalField(
        'цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField('количество товара на складе', default=0,)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name} (категория: {self.category.name})'

    @classmethod
    def get_items(cls):
        return cls.objects.filter(is_active=True, category__is_active=True)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['price']

geekshop/adminapp/forms.py
from django.contrib.auth import get_user_model
from django.forms import ModelForm, HiddenInput

from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product


class AdminShopUserUpdateForm(ShopUserEditForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'password', 'email', 'age', 'avatar', 'is_staff',
                  'is_superuser', 'is_active')

        # def __init__(self, *args, **kwargs):
        #     super().__init__(*args, **kwargs)
        #     for field_name, field in self.fields.items():
        #         field.widget.attrs['class'] = 'form-control'
        #         field.help_text = ''
        #         if field_name.startswith('is_'):
        #             field.widget.attrs['class'] = CheckboxSelectMultiple()


class ProductCategoryCreateForm(ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'category':
                field.widget = HiddenInput()

geekshop/adminapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView

from adminapp.forms import AdminShopUserUpdateForm, ProductCategoryCreateForm, ProductUpdateForm
from mainapp.models import ProductCategory, Product


class SuperUserOnlyMixin:
    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PageTitleMixin:
    page_title_key = 'page_title'
    page_title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.page_title_key] = self.page_title
        return context


@user_passes_test(lambda user: user.is_superuser)
def index(request):
    all_users = get_user_model().objects.all()
    context = {
        'page_title': 'админка/пользователи',
        'all_users': all_users,
    }
    return render(request, 'adminapp/index.html', context)


# @user_passes_test(lambda user: user.is_superuser)
# def user_update(request, user_pk):
#     user = get_object_or_404(get_user_model(), pk=user_pk)
#     if request.method == 'POST':
#         user_form = AdminShopUserUpdateForm(request.POST, request.FILES, instance=user)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('my_admin:index'))
#     else:
#         user_form = AdminShopUserUpdateForm(instance=user)
#
#     context = {
#         'page_title': 'админка/пользователи/редактирование',
#         'user_form': user_form,
#     }
#
#     return render(request, 'adminapp/shopuser_form.html', context)


class ShopUserAdminUpdate(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = get_user_model()
    form_class = AdminShopUserUpdateForm
    success_url = reverse_lazy('my_admin:index')
    pk_url_kwarg = 'user_pk'
    page_title = 'пользователи/редактирование'


@user_passes_test(lambda user: user.is_superuser)
def user_delete(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if not user.is_active or request.method == 'POST':
        if user.is_active:
            user.is_active = False
            user.save()
        return HttpResponseRedirect(reverse('my_admin:index'))
    context = {
        'page_title': 'админка/пользователи/удаление',
        'user': user,
    }
    return render(request, 'adminapp/user_delete.html', context)


# @user_passes_test(lambda user: user.is_superuser)
# def categories(request):
#     context = {
#         'page_title': 'админка/категории',
#         'categories_list': ProductCategory.objects.all()
#     }
#     return render(request, 'adminapp/productcategory_list.html', context)


class ProductCategoryList(SuperUserOnlyMixin, PageTitleMixin, ListView):
    model = ProductCategory
    page_title = 'категории'


class ProductCategoryCreate(SuperUserOnlyMixin, PageTitleMixin, CreateView):
    model = ProductCategory
    form_class = ProductCategoryCreateForm
    success_url = reverse_lazy('my_admin:categories')
    page_title = 'категории/создание'
    # fields = '__all__'
    # template_name = 'adminapp/productcategory_form.html'


class ProductCategoryUpdate(SuperUserOnlyMixin, PageTitleMixin, UpdateView):
    model = ProductCategory
    form_class = ProductCategoryCreateForm
    success_url = reverse_lazy('my_admin:categories')
    page_title = 'категории/редактирование'


class ProductCategoryDelete(SuperUserOnlyMixin, PageTitleMixin, DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('my_admin:categories')
    page_title = 'категории/удаление'


@user_passes_test(lambda user: user.is_superuser)
def category_products(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)
    object_list = category.product_set.all()
    context = {
        'page_title': f'категория {category.name}/продукты',
        'category': category,
        'object_list': object_list,
    }
    return render(request, 'mainapp/category_product_list.html', context)


@user_passes_test(lambda user: user.is_superuser)
def category_product_create(request, category_pk):
    category = get_object_or_404(ProductCategory, pk=category_pk)
    if request.method == 'POST':
        form = ProductUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('my_admin:category_products', kwargs={'pk': category.pk}))
    else:
        form = ProductUpdateForm(initial={'category': category, })

    context = {
        'page_title': 'продукты/создание',
        'form': form,
        'category': category
    }
    return render(request, 'mainapp/product_update.html', context)


@user_passes_test(lambda user: user.is_superuser)
def product_delete(request, pk):
    object = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        object.is_active = False
        object.save()
        return HttpResponseRedirect(reverse('my_admin:category_products', kwargs={'pk': object.category.pk}))

    context = {
        'page_title': 'продукты/удаление',
        'object': object,
    }
    return render(request, 'mainapp/product_delete.html', context)


class ProductDetail(SuperUserOnlyMixin, PageTitleMixin, DetailView):
    model = Product
    page_title = 'админка/продукты'

geekshop/mainapp/views.py
import random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory


# return some random product and render
def get_hot_product():
    product_ids = Product.get_items().values_list('id', flat=True)
    random_id = random.choice(product_ids)
    return Product.objects.get(pk=random_id)
    # return random.choice(Product.objects.all())


def same_product(hot_product):
    return Product.get_items().filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]

def products(request):
    hot_product = get_hot_product()
    context = {
        'page_title': 'каталог',
        'hot_product': hot_product,
        'same_product': same_product(hot_product),
    }
    return render(request, 'products.html', context)


def category(request, pk=None):
    page_num = request.GET.get('page', 1)
    if pk == 0:
        category = {'pk': 0, 'name': 'все', }
        products = Product.get_items()
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = category.product_set.filter(is_active=True)
        # products = Product.objects.filter(category__pk=pk)

    product_paginator = Paginator(products, 3)
    try:
        products = product_paginator.page(page_num)
    except PageNotAnInteger:
        products = product_paginator.page(1)
    except EmptyPage:
        products = product_paginator.page(product_paginator.num_pages)

    context = {
        'page_title': 'товары категории',
        'category': category,
        'products': products,
    }

    return render(request, 'category_products.html', context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'страница продукта',
        'product': product,
    }
    return render(request, 'product_page.html', context)

geekshop/adminapp/templates/mainapp/category_product_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block container %}
 <div class="product_list mx-auto col-6">
   <a class="new_product btn btn-primary"
   href="{% url 'my_admin:category_product_create' category.pk %}">+ новый продукт</a>
   
   {% for object in object_list %}
   <div class="product_record {% if not object.is_active %}not_active{% endif %}">
     <img src="{{ object.image|media_folder_products }}" alt="img">
     <div class="product_name">
       {{ object.name|capfirst }}
     </div>
     <div class="product_desc">
       {{ object.short_desc|capfirst }}
     </div>
     <div class="product_actions">
       <button>
         <a href="{% url 'my_admin:product_view' pk=object.pk %}">подробнее</a>
       </button>
       <button>
         <a href="{#% url 'my_admin:product_update' pk=object.pk %#}">редактировать</a>
       </button>
       <button>
         <a href="{#% url 'my_admin:product_delete' pk=object.pk %#}">удалить</a>
       </button>
     </div>
     <div class="summary">
       <b>цена</b>
       <p>{{ object.price }}</p>
       <b>количество</b>
       <p>{{ object.quantity }}</p>
     </div>
   </div>
   {% endfor %}
 </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block container %}
  <div class="product_read mx-auto col-6">
    <div class="product_name">
      Продукт: <strong>{{ object.category.name|upper }} / {{ object.name|upper }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'product_img/default.jpg' }}" alt="{{ object.name }}">

    <div class="summary">
       <b>цена</b>
       <p>{{ object.price }}</p>
       <b>количество</b>
       <p>{{ object.quantity }}</p>
       <b>в каталоге</b>
       <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
       <p>
           <a href="{#% url 'my_admin:product_update' object.pk %#}" class="btn btn-primary">
        редактировать</a>
       </p>
        <p>
            <a href="{#% url 'my_admin:product_delete' object.pk %#}" class="btn btn-danger">
        удалить</a>
       </p>
       <p>
            <a href="{% url 'my_admin:category_products' object.category_id %}" class="btn btn-primary">
        назад</a>
       </p>
     </div>
      <div class="product_desc">
          <b>краткая информация</b>
          <p>{{ object.short_desc }}</p>
          <br><br>
          <b>подробная информация</b>
          <p>{{ object.description }}</p>
      </div>
  </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new_category_form  mx-auto col-4">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'my_admin:category_products' category.pk %}"
        class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/productcategory_confirm_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
  <div class="user_delete mx-auto col-3">
    Вы уверены, что хотите удалить <b>{{ object.name }}</b>?
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <a href="{% url 'my_admin:categories' %}" class="btn btn-success">
      отмена
    </a>
  </div>
{% endblock %}

geekshop/adminapp/templates/mainapp/productcategory_form.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
<div class="mx-auto col-4">
  <div class="login">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="form-control" type="submit" value="сохранить">
    </form>
    <a href="{% url 'my_admin:categories' %}"
    class="btn btn-primary form-control last">
      к списку категорий
    </a>
  </div>
</div>
{% endblock %}

geekshop/adminapp/templates/mainapp/productcategory_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
  <div class="users_list mx-auto col-4">
    <a href="{% url 'my_admin:category_create' %}" class="btn btn-primary new_user">
      новая категория
    </a>
    {% for category in object_list %}
      <div class="user_name">
          <p><strong>{{ category.name|upper }}</strong></p>
        </div>
        <div>
        {{ category.description }}
      </div>
    <div class="user_record {% if not category.is_active %}not_active{% endif %}">
      <div class="category_actions">
        <a href="{% url 'my_admin:category_products' category.pk %}" class="btn btn-info">
          товары категории
        </a>
        <a href="{% url 'my_admin:category_update' category.pk %}" class="btn btn-primary">
          редактировать
        </a>
        <a href="{% url 'my_admin:category_delete' category.pk %}" class="btn btn-danger">
          удалить
        </a>
      </div>
      <div class="user_record {% if not category.is_active %}not_active{% endif %}">
        <div class="user_role">
          <a href="{% url 'my_admin:category_update' category.pk %}" class="btn btn-primary">
            редактировать
          </a>
          <a href="{% url 'my_admin:category_delete' category.pk %}" class="btn btn-danger">
            удалить
          </a>
        </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}