geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/profile/', authapp.edit, name='edit'),
    path('user/register/', authapp.register, name='register'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:product_pk>/', basketapp.add, name='add'),
    path('remove/<int:basket_item_pk>/', basketapp.remove, name='remove'),
    path('update/<int:basket_item_pk>/<int:quantity>/', basketapp.update),
]

geekshop/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import settings
from .views import main, contact

app_name = 'geekshop'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', main, name='index'),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('', include('social_django.urls', namespace='social')),
    path('my/admin/', include('adminapp.urls', namespace='my_admin')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import category, products, product_page
urlpatterns = [
    path('', products, name='products'),
    path('category/<pk>/', category, name='category'),
    path('product/<pk>/', product_page, name='product_page'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        'имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        'описание',
        blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name} ({self.updated})'

    class Meta:
        verbose_name = 'категория продукта'
        verbose_name_plural = 'категории продукта'
        ordering = ['name']

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE,)
    name = models.CharField('имя', max_length=128,)
    image = models.ImageField(upload_to='product_img', blank=True,)
    short_desc = models.CharField(
        'краткое описание',
        max_length=256,
        blank=True,
    )
    description = models.CharField(
        'описание',
        max_length=500,
        blank=True,
    )
    price = models.DecimalField(
        'цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField('количество товара на складе', default=0,)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name} (категория: {self.category.name})'

    @classmethod
    def get_items(cls):
        return cls.objects.filter(is_active=True, category__is_active=True)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['price']

geekshop/mainapp/views.py
import random
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory


# return some random product and render
def get_hot_product():
    product_ids = Product.get_items().values_list('id', flat=True)
    random_id = random.choice(product_ids)
    return Product.objects.get(pk=random_id)
    # return random.choice(Product.objects.all())


def same_product(hot_product):
    return Product.get_items().filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]

def products(request):
    hot_product = get_hot_product()
    context = {
        'page_title': 'каталог',
        'hot_product': hot_product,
        'same_product': same_product(hot_product),
    }
    return render(request, 'products.html', context)


def category(request, pk=None):
    page_num = request.GET.get('page', 1)
    if pk == 0:
        category = {'pk': 0, 'name': 'все', }
        products = Product.get_items()
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = category.product_set.filter(is_active=True)
        # products = Product.objects.filter(category__pk=pk)

    product_paginator = Paginator(products, 3)
    try:
        products = product_paginator.page(page_num)
    except PageNotAnInteger:
        products = product_paginator.page(1)
    except EmptyPage:
        products = product_paginator.page(product_paginator.num_pages)

    context = {
        'page_title': 'товары категории',
        'category': category,
        'products': products,
    }

    return render(request, 'category_products.html', context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'страница продукта',
        'product': product,
    }
    return render(request, 'product_page.html', context)

geekshop/mainapp/templates/category_products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="hero-white">
		{% include 'includes/inc_menu.html' %}
			<a href="#" class="basket"></a>
	</div>

	<div class="details">
		{% include 'includes/inc_catalog.html' %}

		<div class="related">
			<div class="title clearfix">
				<h2>Продукты категории {{ category.name|upper }}</h2>
				<div class="paginator">
					{% if products.has_previous %}
						<a href="{% url 'category' category.pk %}?page={{ products.previous_page_number }}"> << </a>
					{% endif %}
					<span class="current">страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
					{% if products.has_next %}
						<a href="{% url 'category' category.pk %}?page={{ products.next_page_number }}"> >> </a>
					{% endif %}
				</div>
			</div>
			<div class="related-products clearfix">
				{% for product in products %}
					<div class="block">
					<a href="{% url 'product_page' product.pk %}">
						<img src="/media/{{ product.image }}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>{{ product.name|capfirst }}</h4>
							<p>{{ product.short_desc|capfirst }}</p>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

geekshop/mainapp/templates/product_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="hero-white">
		{% include 'includes/inc_menu.html' %}
			<a href="#" class="basket"></a>
	</div>

	<div class="details">
		{% include 'includes/inc_catalog.html' %}


		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="/media/{{ product.image }}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ product.image }}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">{{ product.name|capfirst }}</h3>
				<br>
				<p class="price">{{ product.price }}<span>руб</span></p>
				<a href="{% url 'basket:add' product.pk %}" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>{{ product.short_desc }}</p>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

geekshop/mainapp/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="hero-white">
		{% include 'includes/inc_menu.html' %}
			<a href="#" class="basket"></a>
	</div>

	<div class="details">
		{% include 'includes/inc_catalog.html' %}


		<div class="details-products">
			<div class="details-slider">
				<div class="slider-product">
					<img src="/media/{{ hot_product.image }}">
				</div>
				<div class="slider-control">
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt="">
							<div class="text"></div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/media/{{ hot_product.image }}" alt="">
							<div class="text"></div>
						</a>
					</div>
				</div>
			</div>

			<div class="description">
				<h3 class="big-bold">{{ hot_product.name|capfirst }}</h3>
				<h3 class="red">горячее предложение</h3>
				<p class="price">{{ hot_product.price }}<span>руб</span></p>
				<a href="{% url 'product_page' hot_product.pk %}" class="red-button">
					заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
				</a>
				<div class="description-text">
					<p>{{ hot_product.short_desc }}</p>
				</div>
			</div>
		</div>

		<div class="related">
			<div class="title clearfix">
				<h2>Похожие продукты</h2>
				<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>
			<div class="related-products clearfix">
				{% for product in same_product %}
					<div class="block">
						<a href="{% url 'product_page' product.pk %}">
							<img src="/media/{{ product.image }}" alt="img">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>{{ product.name }}</h4>
								<p>{{ product.short_desc }}</p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}